# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'mf-ble-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mf-ble-app
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'mf-ble-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mf-ble-appUITests' do
    # Pods for testing
  end

end
